services:
  # Allow connections outside the docker network.
  bp-sd-search-api:
    ports:
      - "8000:8000"
  bp-postgres:
    ports:
      - "5434:5434"
  opensearch:
    ports:
      - "9200:9200"
  opensearch-dashboards:
    ports:
      - "5601:5601"
