[tox]
envlist = ruff, mypy, pytest
skipsdist = True

[testenv:ruff]
basepython = python3.14
runner = uv-venv-lock-runner
extras = tox
package = skip
allowlist_externals = ruff
commands =
    ruff format search_api
    ruff check search_api --fix
    ruff format tests
    ruff check tests --fix

[testenv:mypy]
basepython = python3.14
runner = uv-venv-lock-runner
extras = tox
allowlist_externals = mypy
commands = mypy search_api

[testenv:pytest]
basepython = python3.14
runner = uv-venv-lock-runner
extras = tox
allowlist_externals = pytest
commands = pytest -x --cov=search_api tests/unit/
