filtering_groups:
  - id: description
    label: "Description"
    description: ""
  - id: subject
    label: "Subject & specimen"
    description: ""
  - id: sample
    label: "Sample & block"
    description: ""
  - id: staining
    label: "Staining"
    description: ""
  - id: clinical
    label: "Clinical"
    description: ""
  - id: non_clinical
    label: "Non-clinical"
    description: ""
  - id: finding_details
    label: "Finding details"
    description: ""
    parent: non_clinical
