filtering_groups:
  - id: description
    label: "Description"
    description: ""
  - id: subject
    label: "Subject & specimen"
    description: ""
  - id: sample
    label: "Sample & block"
    description: ""
  - id: staining
    label: "Staining"
    description: ""
    border: true
  - id: clinical
    label: "Clinical"
    description: ""
    border: true
  - id: non_clinical
    label: "Non-clinical"
    description: ""
    border: true
