# Qualifiers that label fields in a nested group.
#
# A qualifier is indexed alongside the values in a nested group. One
# group can have several qualifier values. A query can restrict the
# search to certain qualifier values only.
filtering_qualifiers:
  - id: observation
    label: "Observation"
    values: [ confirmed, candidate ]
    groups: [ diagnosis, finding ]
    description: >-
      How an observation is linked to the image. Applies to clinical diagnoses
      and non-clinical findings. A confirmed observation is known to apply to 
      the image. A candidate observation is known to apply to at least one image 
      in a set of images, but not necessarily to all of them.
