apiVersion: v1
kind: Secret
metadata:
  name: sd-search-api-credentials
  namespace: sd-search
type: Opaque
stringData:
  POSTGRES_PASSWORD: ""
  OPENSEARCH_PASSWORD: ""
  ADMIN_KEY: ""

  # LLM API key (only required when FEATURE_AI=true)
  LLM_API_KEY: ""

  # OIDC Relying Party login
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""

  # JWT signing key for session tokens; must be base64-encoded
  JWT_KEY: ""
