apiVersion: v1
kind: Service
metadata:
  name: sd-search-api
  namespace: sd-search
  labels:
    app: sd-search-api
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: sd-search-api
